namespace Python.Runtime.Native
{
    using System;
    using System.Globalization;
    using System.Linq;
    using System.Reflection;

    static class ABI
    {
        // GIL builds only. FT splits the refcount; Refcount uses Py_REFCNT.
        public static int RefCountOffset { get; private set; }

        // Added to generated TypeOffsets. FT PyObject_HEAD is 16 bytes larger.
        public static int ObjectHeadOffset { get; private set; }

        public static bool IsFreeThreaded { get; private set; }

        internal static void Initialize(Version version)
        {
            IsFreeThreaded = DetectFreeThreaded();
            RefCountOffset = IsFreeThreaded ? -1 : ProbeRefCountOffset();
            ObjectHeadOffset = IsFreeThreaded ? 16 : RefCountOffset;

            string offsetsClassSuffix = string.Format(CultureInfo.InvariantCulture,
                                                      "{0}{1}", version.Major, version.Minor);

            var thisAssembly = Assembly.GetExecutingAssembly();

            const string nativeTypeOffsetClassName = "Python.Runtime.NativeTypeOffset";
            string className = "Python.Runtime.TypeOffset" + offsetsClassSuffix;
            Type nativeOffsetsClass = thisAssembly.GetType(nativeTypeOffsetClassName, throwOnError: false);
            Type typeOffsetsClass =
                // Try platform native offsets first. It is only present when generated by setup.py
                nativeOffsetsClass ?? thisAssembly.GetType(className, throwOnError: false);
            if (typeOffsetsClass is null)
            {
                var types = thisAssembly.GetTypes().Select(type => type.Name).Where(name => name.StartsWith("TypeOffset"));
                string message = $"Searching for {className}, found {string.Join(",", types)}.";
                throw new NotSupportedException($"Python ABI v{version} is not supported: {message}");
            }

            var typeOffsets = (ITypeOffsets)Activator.CreateInstance(typeOffsetsClass);
            TypeOffset.Use(typeOffsets, nativeOffsetsClass == null ? ObjectHeadOffset : 0);
        }

        /// <summary>
        /// True when the running interpreter is a Py_GIL_DISABLED (free-threaded) build.
        /// </summary>
        static bool DetectFreeThreaded()
        {
            // sys._is_gil_enabled() was added in Python 3.13; absent means GIL build.
            using var sys = Runtime.PyImport_ImportModule("sys");
            if (sys.IsNull()) { Runtime.PyErr_Clear(); return false; }
            using var func = Runtime.PyObject_GetAttrString(sys.Borrow(), "_is_gil_enabled");
            if (func.IsNull()) { Runtime.PyErr_Clear(); return false; }
            using var args = Runtime.PyTuple_New(0);
            using var result = Runtime.PyObject_Call(func.Borrow(), args.Borrow(), default);
            if (result.IsNull()) { Runtime.PyErr_Clear(); return false; }
            return Runtime.PyObject_IsTrue(result.Borrow()) == 0;
        }

        /// <summary>
        /// Locates the offset of <c>ob_refcnt</c> inside <c>PyObject</c> by allocating a
        /// fresh list and scanning for its refcount value of 1.  GIL builds only.
        /// </summary>
        static unsafe int ProbeRefCountOffset()
        {
            using var tempObject = Runtime.PyList_New(0);
            IntPtr* tempPtr = (IntPtr*)tempObject.DangerousGetAddress();
            int offset = 0;
            while(tempPtr[offset] != (IntPtr)1)
            {
                offset++;
                if (offset > 100)
                    throw new InvalidProgramException("PyObject_HEAD could not be found withing reasonable distance from the start of PyObject");
            }
            return offset * IntPtr.Size;
        }
    }
}
