package:
    name: pythonnet
    version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('-dev', '.dev') }}

build:
    skip: True  # [not win]
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
    {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - clr

about:
   home: https://github.com/pythonnet/pythonnet
   license: ZPL
