name: NuGet Preview Release

on:
  schedule:
  - cron: "5 4 3 */1 *" # once a month, at 4:05 on 3rd
  workflow_dispatch:

jobs:
  release:
    name: Release Preview
    runs-on: ubuntu-latest
    environment: NuGet
    timeout-minutes: 30

    env:
      PYTHONNET_SHUTDOWN_MODE: Normal

    steps:
      - name: Get Date
        run: |
          echo "DATE_VER=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Set up Python 3.11
        uses: astral-sh/setup-uv@v7
        with:
          python-version: cpython-3.11
          cache-python: true
          activate-environment: true
          enable-cache: true

      - name: Install dependencies
        run: uv sync --managed-python

      - name: Set Python DLL path
        run: |
          echo PYTHONNET_PYDLL=$(python -m find_libpython) >> $GITHUB_ENV

      - name: Python Tests
        run: pytest

      - name: Embedding tests
        run: dotnet test --runtime any-ubuntu src/embed_tests/

      - name: Pack
        run: dotnet pack --configuration Release --version-suffix preview${{env.DATE_VER}} --output "Release-Preview"

      - name: Publish NuGet
        run: |
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_MONTHLY }} Release-Preview/*.nupkg
          dotnet nuget push --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_MONTHLY }} Release-Preview/*.snupkg
